# Site Settings
baseurl: ""
url : "https://hih0422.github.io/django"

# Blog Settings
theme_settings :
  title : Seongmin Django
  favicon : django/assets/favicon.ico

  # Profile Settings
  profile :
    image : django/assets/img/smile.png
    username : Seongmin Kim
    description : python php javascript
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: hih0422
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
